version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - sudopem="sudo $(aws ecr get-login --no-include-email --region us-east-1)"
      - eval $sudopem
      - REPOSITORY_URI=976968573664.dkr.ecr.us-east-1.amazonaws.com/docker-teste:latest
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - npm run -s build
  post_build:
    commands:
      - echo $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - sudo docker push $REPOSITORY_URI:latest
      - sudo docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"docker-teste","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json