version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - npm run build
      - echo Prestarting...
      - npm run prestart
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting application
      - npm run start
artifacts:
  files:
    - ./src/index.js