version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo listing directories.
      - ls
      - echo Building...
      - npm run -s build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting application
      - echo dist
      - ls 
      - echo ../dist/
      - cd .. && ls .
      - node dist
artifacts:
  files:
    - ./src/index.js