version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - npm run -s build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./src/index.js