version: 0.2

phases:
  install:
    commands:
      - echo Entering superuser...
      - sudo su 
      - echo Installing dependencies...
      - sudo npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - npm run -s build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting application
      - echo dist
      - ls 
      - echo ../dist/
      - cd .. && ls .

      - node dist
artifacts:
  files:
    - ./src/index.js