version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run start
artifacts:
  files:
    - src/index.js